id: P009578
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:01.335493
source_metadata:
  id: bdr:W1KG25150
  title: མཁར་ནག་ཆོས་འབྱུང།
  author: ''
  volumes:
    1c5d699f53fa4c5bbe44e0512576c3c8:
      image_group_id: I1KG25152
      title: ''
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
